### ISSUE TITLE
expected key word error

### ISSUE THREAD

**Issue by amirabedii** [mbi2gs/netlogo-matlab-extension#6]
Hi
I'm using netlogo 5.0.3 and matlab r2015b. when i use "extensions [matlab]" it works and a matlab window appears, but when i use a simple command like "matlab:eval "a = 1 ;"" netlogo prompts expected keyword error. what should i do?

**Comment by mbi2gs** [comment]
Hi, glad to hear from you. I'm in the process of moving to a new job, and
I'm not really actively using matnet as a result. I would recommend, if
possible, using a legacy version of netlogo and trying that. Let me know if
that helps.

Best,
Matt

**Comment by amirabedii** [comment]
Oh, after doing several solutions, it is cleared that a small (or big) funny mistake caused this problem. I hadn't used the command in the structure of "to go --- end"!
thank you for your quick response.

**Comment by mbi2gs** [comment]
Glad you got it working!

best,
Matt
